### ISSUE TITLE
Tied parameters for question and answer in attention model

### ISSUE THREAD

**Issue by shwetgarg** [dandxy89/DeepLearning_MachineLearning#10]
Thank you for a such a nice implementation. In this implementation you have different weights for both question and answer BiLSTMs. I was wondering how to implement similar attention model with tied BiLSTM parameters in keras. Any pointer will be helpful. Thanks !!!

**Comment by dandxy89** [comment]
Take a look at this -> https://keras.io/getting-started/functional-api-guide/#shared-layers

Dan
