### ISSUE TITLE
Adding more example of NLP classifications

### ISSUE THREAD

**Issue by dandxy89** [dandxy89/DeepLearning_MachineLearning#7]
Drop me a message (email) or comment here, if you require any additional examples.

**Comment by dandxy89** [comment]
Going to need some more information than that. 

Can you provide more examples and better context of what you are trying to achieve?

**Comment by vinayakumarr** [comment]
I have seen lstm examples on text data set. I am just a beginner. each row is a feature set of particular file malware or not malware. I have around 10000 rows.

**Comment by vinayakumarr** [comment]
I have seen example for rnn spoken language understanding. I have my own data set and i would like to try towards this. But he is not given any information regarding this. 

https://github.com/mesnilgr/is13

Do you know how to apply our own data set for the above link code.

**Comment by dandxy89** [comment]
Can you tell me more information about your dataset, what are you trying to do?

From what you have described, you have a binary classification task to identify if a particular piece of text is malware or not.

The example within this repository should be sufficient if you have the raw texts.
